# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: portable70.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='portable70.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10portable70.proto\"V\n\x05\x46rame\x12\x19\n\x06status\x18\x01 \x01(\x0b\x32\x07.StatusH\x00\x12\x13\n\x03log\x18\x02 \x01(\x0b\x32\x04.LogH\x00\x12\x15\n\x04rssi\x18\x03 \x01(\x0b\x32\x05.RSSIH\x00\x42\x06\n\x04\x64\x61ta\"\x08\n\x06Status\"\x14\n\x04RSSI\x12\x0c\n\x04rssi\x18\x01 \x01(\x05\"\x16\n\x03Log\x12\x0f\n\x07message\x18\x01 \x01(\t\"f\n\x0cUpdateConfig\x12\x11\n\tfrequency\x18\x01 \x01(\r\x12\x0e\n\x06offset\x18\x02 \x01(\r\x12\x10\n\x08\x63\x61llsign\x18\x03 \x01(\t\x12\x0f\n\x07persist\x18\x04 \x01(\x08\x12\x10\n\x08rssiDump\x18\x05 \x01(\x08\"H\n\x06Update\x12\x1f\n\x06\x63onfig\x18\x01 \x01(\x0b\x32\r.UpdateConfigH\x00\x12\x15\n\x04mode\x18\x02 \x01(\x0e\x32\x05.ModeH\x00\x42\x06\n\x04\x64\x61ta*$\n\x04Mode\x12\x0c\n\x08TRACKING\x10\x00\x12\x06\n\x02IQ\x10\x01\x12\x06\n\x02\x43W\x10\x02\x62\x06proto3')
)

_MODE = _descriptor.EnumDescriptor(
  name='Mode',
  full_name='Mode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TRACKING', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IQ', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CW', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=342,
  serialized_end=378,
)
_sym_db.RegisterEnumDescriptor(_MODE)

Mode = enum_type_wrapper.EnumTypeWrapper(_MODE)
TRACKING = 0
IQ = 1
CW = 2



_FRAME = _descriptor.Descriptor(
  name='Frame',
  full_name='Frame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='Frame.status', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='log', full_name='Frame.log', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rssi', full_name='Frame.rssi', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='data', full_name='Frame.data',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=20,
  serialized_end=106,
)


_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=116,
)


_RSSI = _descriptor.Descriptor(
  name='RSSI',
  full_name='RSSI',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rssi', full_name='RSSI.rssi', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=118,
  serialized_end=138,
)


_LOG = _descriptor.Descriptor(
  name='Log',
  full_name='Log',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='Log.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=162,
)


_UPDATECONFIG = _descriptor.Descriptor(
  name='UpdateConfig',
  full_name='UpdateConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frequency', full_name='UpdateConfig.frequency', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='offset', full_name='UpdateConfig.offset', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='callsign', full_name='UpdateConfig.callsign', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='persist', full_name='UpdateConfig.persist', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rssiDump', full_name='UpdateConfig.rssiDump', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=266,
)


_UPDATE = _descriptor.Descriptor(
  name='Update',
  full_name='Update',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='config', full_name='Update.config', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mode', full_name='Update.mode', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='data', full_name='Update.data',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=268,
  serialized_end=340,
)

_FRAME.fields_by_name['status'].message_type = _STATUS
_FRAME.fields_by_name['log'].message_type = _LOG
_FRAME.fields_by_name['rssi'].message_type = _RSSI
_FRAME.oneofs_by_name['data'].fields.append(
  _FRAME.fields_by_name['status'])
_FRAME.fields_by_name['status'].containing_oneof = _FRAME.oneofs_by_name['data']
_FRAME.oneofs_by_name['data'].fields.append(
  _FRAME.fields_by_name['log'])
_FRAME.fields_by_name['log'].containing_oneof = _FRAME.oneofs_by_name['data']
_FRAME.oneofs_by_name['data'].fields.append(
  _FRAME.fields_by_name['rssi'])
_FRAME.fields_by_name['rssi'].containing_oneof = _FRAME.oneofs_by_name['data']
_UPDATE.fields_by_name['config'].message_type = _UPDATECONFIG
_UPDATE.fields_by_name['mode'].enum_type = _MODE
_UPDATE.oneofs_by_name['data'].fields.append(
  _UPDATE.fields_by_name['config'])
_UPDATE.fields_by_name['config'].containing_oneof = _UPDATE.oneofs_by_name['data']
_UPDATE.oneofs_by_name['data'].fields.append(
  _UPDATE.fields_by_name['mode'])
_UPDATE.fields_by_name['mode'].containing_oneof = _UPDATE.oneofs_by_name['data']
DESCRIPTOR.message_types_by_name['Frame'] = _FRAME
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
DESCRIPTOR.message_types_by_name['RSSI'] = _RSSI
DESCRIPTOR.message_types_by_name['Log'] = _LOG
DESCRIPTOR.message_types_by_name['UpdateConfig'] = _UPDATECONFIG
DESCRIPTOR.message_types_by_name['Update'] = _UPDATE
DESCRIPTOR.enum_types_by_name['Mode'] = _MODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Frame = _reflection.GeneratedProtocolMessageType('Frame', (_message.Message,), {
  'DESCRIPTOR' : _FRAME,
  '__module__' : 'portable70_pb2'
  # @@protoc_insertion_point(class_scope:Frame)
  })
_sym_db.RegisterMessage(Frame)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), {
  'DESCRIPTOR' : _STATUS,
  '__module__' : 'portable70_pb2'
  # @@protoc_insertion_point(class_scope:Status)
  })
_sym_db.RegisterMessage(Status)

RSSI = _reflection.GeneratedProtocolMessageType('RSSI', (_message.Message,), {
  'DESCRIPTOR' : _RSSI,
  '__module__' : 'portable70_pb2'
  # @@protoc_insertion_point(class_scope:RSSI)
  })
_sym_db.RegisterMessage(RSSI)

Log = _reflection.GeneratedProtocolMessageType('Log', (_message.Message,), {
  'DESCRIPTOR' : _LOG,
  '__module__' : 'portable70_pb2'
  # @@protoc_insertion_point(class_scope:Log)
  })
_sym_db.RegisterMessage(Log)

UpdateConfig = _reflection.GeneratedProtocolMessageType('UpdateConfig', (_message.Message,), {
  'DESCRIPTOR' : _UPDATECONFIG,
  '__module__' : 'portable70_pb2'
  # @@protoc_insertion_point(class_scope:UpdateConfig)
  })
_sym_db.RegisterMessage(UpdateConfig)

Update = _reflection.GeneratedProtocolMessageType('Update', (_message.Message,), {
  'DESCRIPTOR' : _UPDATE,
  '__module__' : 'portable70_pb2'
  # @@protoc_insertion_point(class_scope:Update)
  })
_sym_db.RegisterMessage(Update)


# @@protoc_insertion_point(module_scope)
